-- ABC ANALYSIS -- USED FOR INVENTORY ANALYSIS 
WITH REVENUE_CTE AS 
( 
SELECT SKU , 
		SUM(UNITS_SOLD * SELLING_PRICE) AS REVENUE
FROM FMCG 
GROUP BY SKU
) 
,
  ABC_CTE AS 
(
SELECT SKU , 
	   REVENUE ,
       SUM(REVENUE)OVER(ORDER BY REVENUE DESC) AS RUNNING_REVENUE ,
       SUM(REVENUE)OVER() AS TOTAL_RUNNING_REVENUE 
FROM REVENUE_CTE
)
SELECT SKU , 
	   REVENUE,
       ROUND((RUNNING_REVENUE / TOTAL_RUNNING_REVENUE) * 100 , 2) AS CUMULATIVE_PERCENTAGE ,
CASE 
   WHEN (RUNNING_REVENUE / TOTAL_RUNNING_REVENUE) <= 0.80 THEN 'A'
   WHEN (RUNNING_REVENUE / TOTAL_RUNNING_REVENUE) <= 0.95 THEN 'B'
ELSE 'C'
END AS ABC_CATEGORY
FROM ABC_CTE 
ORDER BY REVENUE DESC
;
-- REVENUE RANKING USING RANK 

WITH CTE1 AS 
(
SELECT SKU , 
       SUM(UNITS_SOLD * SELLING_PRICE) AS REVENUE 
 FROM FMCG 
 GROUP BY SKU 
),
CTE2 AS 
(
SELECT SKU , 
	   REVENUE,
       DENSE_RANK()OVER(ORDER BY REVENUE DESC) AS RANKING_REVENUE
FROM CTE1
)
SELECT * FROM CTE2
LIMIT 3
 ;
 
 -- month-over-month 
 -- current month revenue - previous month revenue / previous month revenue * 100 
 
 with monthly_sales as 
 (
 select 
	   year(`date`) as `year` ,
       MONTH(`date`) as `month`,
       sum(units_sold*selling_price) AS REVENUE
FROM FMCG
GROUP BY YEAR(`DATE`),
MONTH(`DATE`)
)
SELECT
     `YEAR`,
     `MONTH`,
     REVENUE,
     LAG(REVENUE)OVER(ORDER BY `YEAR`,`MONTH`) AS PREVIOUS_MONTH_REVENUE,
ROUND((REVENUE - LAG(REVENUE)OVER(ORDER BY `YEAR`,`MONTH`)/LAG(REVENUE)OVER(ORDER BY `YEAR`,`MONTH`))*100,2) AS MOM_GROWTH_PERCENT
FROM MONTHLY_SALES
ORDER BY `YEAR` , `MONTH`
 ;
 
 
 
 
 
 