-- REAL LIFE BUSINESS QUESTIONS 
-- QUESTION :-1 
-- WHICH REGION GENERATE A HIGHEST REVENUE WITHOUT PROMOTION  

SELECT REGION , 
	   SUM(UNITS_SOLD * SELLING_PRICE) AS REVENUE
       FROM FMCG 
       WHERE PROMOTION_FLAG = 0 
       GROUP BY REGION;
       
-- QUESTION :- 2
-- DOES PROMOTION INCREASE UNITS_SOLD
SELECT PROMOTION_FLAG ,
       COUNT(*) AS TOTAL_RECORDS,
       ROUND(AVG(UNITS_SOLD),2) 
;


-- YES , PROMOTION INCREASES A UNITS_SOLD

SELECT * FROM FMCG
;
-- QUESTION : - 3
-- WHICH CHANNEL BENEFITS THE MOST FROM PROMOTIONS ?
 SELECT `CHANNEL`,
         PROMOTION_FLAG,
 CASE 
 WHEN PROMOTION_FLAG = 1 THEN SUM(UNITS_SOLD)
 END AS BENEFIT_WITH_PROMOTION
 FROM fmcg
 WHERE PROMOTION_FLAG = 1
 GROUP BY `CHANNEL` ,PROMOTION_FLAG
 ORDER BY BENEFIT_WITH_PROMOTION DESC
 ;
select * from fmcg  ;
 -- Question - 4 
-- which brands frequently faces stock - outs ?

SELECT BRAND , MIN(STOCK_AVAILABLE) FROM FMCG 
WHERE STOCK_AVAILABLE <= 100
GROUP BY BRAND   
ORDER BY MIN(STOCK_AVAILABLE)
LIMIT 10 ;

-- Question - 5
-- Slow Moving Inventory -- High Stock Available but low Sales 
 WITH CTE AS 
 (
SELECT SKU ,  STOCK_AVAILABLE , UNITS_SOLD ,
CASE 
      WHEN STOCK_AVAILABLE > 200 AND 
      UNITS_SOLD < 50 THEN "SLOW INVENTORY" 
      ELSE "NORMAL INVENTORY"
END AS INVENTORY_INSPECTION 
FROM FMCG
)
SELECT SKU ,  STOCK_AVAILABLE , UNITS_SOLD , INVENTORY_INSPECTION FROM CTE
WHERE INVENTORY_INSPECTION LIKE "%SLOW%" ;

-- Question -6 
-- Which sku has highest delivery efficiency ?

select * from fmcg ;
#select min(delivery_days) from fmcg 

SELECT SKU , DELIVERY_DAYS , 
 CASE 
      WHEN DELIVERY_DAYS > 
(
      SELECT AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS  FROM FMCG
)
      THEN 'HIGH_DELIVERY_EFFICIENCY'
      ELSE "LOW EFFICIENCY"
END AS DEL_EFFICIENCY
FROM FMCG
;

-- Question 7 
-- find brands with declining monthly sales 
-- QUERY BELOW IS CORRECT BUT NOT GIVING REQUIRED RESULT
#SELECT BRAND ,
#	   YEAR(`DATE`),
#	   MONTH(`DATE`) AS MONTHS,
#      SUM(TRIM(UNITS_SOLD)) ,
#   ROW_NUMBER()OVER(PARTITION BY BRAND ORDER BY MONTH(`DATE`) , SUM(TRIM(UNITS_SOLD))  DESC) AS TOTAL_SALE
#FROM FMCG 
#GROUP BY BRAND , 
#      YEAR(`DATE`)
#ORDER BY YEAR(`DATE`);
       
       
-- 
WITH CTE1 AS 
( 
SELECT BRAND, 
		YEAR(`DATE`) AS YEARS,
        MONTH(`DATE`) AS MONTHS,
        SUM(UNITS_SOLD) AS TOTAL_UNITS_SOLD 
FROM FMCG
GROUP BY BRAND , 
	  YEAR(`DATE`) ,
      MONTH(`DATE`)
) ,
CTE2 AS 
( 
SELECT  BRAND, 
		YEARS,
        MONTHS,
        TOTAL_UNITS_SOLD ,
        LAG(TOTAL_UNITS_SOLD)OVER(PARTITION BY BRAND ORDER BY YEARS , MONTHS)
        AS PREVIOUS_MONTHS_SALES
FROM CTE1
)
SELECT * FROM CTE2 
WHERE TOTAL_UNITS_SOLD < PREVIOUS_MONTHS_SALES ;


-- Question - 8
-- find region with consistently increasing sales.

WITH CTE1 AS 
(
SELECT REGION , 
       UNITS_SOLD AS TOTAL_SALES 
	   FROM FMCG
	   GROUP BY REGION  , TOTAL_SALES      
),
CTE2 AS 
(
SELECT REGION , 
       TOTAL_SALES,
       LAG(TOTAL_SALES)OVER(PARTITION BY REGION) AS PREVIOUS_YEAR_SALES
       FROM CTE1
)
SELECT* from cte2
;
SELECT* from fmcg;

 -- Question - 9
 -- Retail vs Ecommerce
 # on the basis of units sold

SELECT `CHANNEL` ,
CASE 
    WHEN `CHANNEL` = 'RETAIL' THEN SUM(UNITS_SOLD) 
    WHEN `CHANNEL` = 'E-COMMERCE' THEN SUM(UNITS_SOLD)
END AS TOTAL_UNITS_SOLD
FROM FMCG 
GROUP BY `CHANNEL` ;
-- FEEDBACK -- E-COMMERCE HAS MORE SALES THEN RETAIL 

-- ON THE BASIS OF DELIVERED_QTY 
SELECT `CHANNEL` ,
CASE 
    WHEN `CHANNEL` = 'RETAIL' THEN SUM(DELIVERED_QTY) 
    WHEN `CHANNEL` = 'E-COMMERCE' THEN SUM(DELIVERED_QTY)
END AS TOTAL_ITEM_DELIVERED 
FROM FMCG 
GROUP BY `CHANNEL` 
ORDER BY TOTAL_ITEM_DELIVERED DESC;

-- FEEDBACK -- RETAIL HAS MORE ITEM DELIVERED alter

-- Question - 10 

-- pivot revenue by channel

SELECT YEAR(`DATE`) AS YEAR,
	   MONTH(`DATE`) AS MONTH,
SUM(CASE 
       WHEN `CHANNEL` = 'RETAIL' 
       THEN UNITS_SOLD * SELLING_PRICE 
       ELSE 0 
	END) AS RETAIL_REVENUE ,
SUM(CASE 
       WHEN `CHANNEL` = 'DISCOUNT' 
       THEN UNITS_SOLD * SELLING_PRICE 
       ELSE 0 
	END) AS DISCOUNT_REVENUE ,
SUM(CASE 
	   WHEN `CHANNEL` = 'E-COMMERCE'  
       THEN UNITS_SOLD * SELLING_PRICE 
       ELSE 0 
	END) AS E_COMMERCE_REVENUE 
FROM FMCG 
GROUP BY 
    YEAR(`DATE`) ,
    MONTH(`DATE`)
ORDER BY YEAR,
	    MONTH ;